/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mypkg;

import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.core.config.Configurator;

import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.RealMatrix;

import util.WahoovianMatrix;

public class App {

    private static final Logger logger = LogManager.getLogger();

    public static void main(String[] args) {
        Configurator.setLevel(logger.getName(), Level.TRACE);
        logger.info("Starting Application");

        //first operation
        double[][] m1_data = new double[][] {
            new double[]{7d, 2d, 4d, 7d},
            new double[]{3d, 9d, 3d, 1d},
        };
        RealMatrix wamatrix = new Array2DRowRealMatrix(m1_data);
        RealMatrix wahoovianMatrix1 = WahoovianMatrix.wahoovian(wamatrix);
        System.out.println("wahoovian matrix: " + wahoovianMatrix1);

        //second operation
        double[][] m2_data = new double[][] {
            new double[]{7d, 2d, 9d},
            new double[]{3d, 4d, 1d},
            new double[]{8d, 5d, 6d},
        };
        RealMatrix hoomatrix = new Array2DRowRealMatrix(m2_data);
        RealMatrix wahoovianMatrix2 = WahoovianMatrix.wahoovian(hoomatrix);
        System.out.println("wahoovian matrix: " + wahoovianMatrix2);

        //end
        logger.info("Exiting Application");
      
    }
}
